<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-05-31T20:39:06 IST" name="Suite" finished-at="2022-05-31T20:39:13 IST" duration-ms="6623">
    <groups>
    </groups>
    <test started-at="2022-05-31T20:39:06 IST" name="Test" finished-at="2022-05-31T20:39:13 IST" duration-ms="6623">
      <class name="com.saucedemo.testclasses.TC01New">
        <test-method is-config="true" signature="setup(java.lang.String)[pri:0, instance:com.saucedemo.testclasses.TC01New@7e7be63f]" started-at="2022-05-31T20:39:07 IST" name="setup" finished-at="2022-05-31T20:39:11 IST" duration-ms="4746" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method is-config="true" signature="login()[pri:0, instance:com.saucedemo.testclasses.TC01New@7e7be63f]" started-at="2022-05-31T20:39:11 IST" name="login" finished-at="2022-05-31T20:39:12 IST" duration-ms="587" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method signature="loginFunctionalitytest()[pri:2, instance:com.saucedemo.testclasses.TC01New@7e7be63f]" started-at="2022-05-31T20:39:12 IST" name="loginFunctionalitytest" finished-at="2022-05-31T20:39:12 IST" duration-ms="17" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[**TTest case has passed expected [ Labs] but found [Swag Labs]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: **TTest case has passed expected [ Labs] but found [Swag Labs]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at com.saucedemo.testclasses.TC01New.loginFunctionalitytest(TC01New.java:45)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginFunctionalitytest -->
        <test-method is-config="true" signature="logout()[pri:0, instance:com.saucedemo.testclasses.TC01New@7e7be63f]" started-at="2022-05-31T20:39:12 IST" name="logout" finished-at="2022-05-31T20:39:13 IST" duration-ms="470" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logout -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:com.saucedemo.testclasses.TC01New@7e7be63f]" started-at="2022-05-31T20:39:13 IST" name="teardown" finished-at="2022-05-31T20:39:13 IST" duration-ms="350" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
        <test-method is-config="true" signature="garbagecollection()[pri:0, instance:com.saucedemo.testclasses.TC01New@7e7be63f]" started-at="2022-05-31T20:39:13 IST" name="garbagecollection" finished-at="2022-05-31T20:39:13 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- garbagecollection -->
      </class> <!-- com.saucedemo.testclasses.TC01New -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
